---
apiVersion: v1
kind: Secret
metadata:
  name: dell-badauth
  namespace: oran-hwmgr-plugin
type: kubernetes.io/basic-auth
data:
  username: YWRtaW4=
  password: YmFkcGFzcw==
---
apiVersion: hwmgr-plugin.oran.openshift.io/v1alpha1
kind: HardwareManager
metadata:
  name: dell-badauth
  namespace: oran-hwmgr-plugin
spec:
  adaptorId: dell-hwmgr
  dellData:
    clientId: myclient
    authSecret: dell-badauth
    apiUrl: https://myserver.example.com:443/
