apiVersion: o2ims-hardwaremanagement.oran.openshift.io/v1alpha1
kind: NodePool
metadata:
  name: np1
  namespace: oran-hwmgr-plugin
spec:
  cloudID: testcloud-1
  hwMgrId: loopback-1
  location: ottawa
  nodeGroup:
  - hwProfile: profile-spr-single-processor-64G
    name: controller
    size: 1
    resourcePoolId: xyz-master
    role: master
  - hwProfile: profile-spr-dual-processor-128G
    name: worker
    size: 0
    resourcePoolId: xyz-worker
    role: worker
  site: building-1
